const { test } = require('node:test');
const assert = require('node:assert/strict');
const { _electron: electron } = require('playwright');
const { mkdtempSync, rmSync, readFileSync, existsSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join, resolve } = require('node:path');
const { execFileSync } = require('node:child_process');

test('Electron: local terminal, reconnect, machine settings and relaunch', { timeout: 60000 }, async () => {
  const home = mkdtempSync(join(tmpdir(), 'wangcai-desktop-test-'));
  const env = { ...process.env, HOME: home, SHELL: '/bin/bash' };
  delete env.ELECTRON_RUN_AS_NODE;
  let desktop;
  let devServer;
  const launch = async () => {
    desktop = await electron.launch({ args: ['desktop', `--user-data-dir=${join(home, 'electron-data')}`], env });
    const page = await desktop.firstWindow();
    page.on('pageerror', (error) => console.error('UI error:', error));
    await page.waitForFunction(() => { const button = document.querySelector('[aria-label="新建工作区"]'); return button && !button.disabled; });
    assert.equal(await page.title(), '旺财');
    assert.equal(await desktop.evaluate(({ app }) => app.getName()), '旺财');
    return page;
  };
  try {
    let page = await launch();
    await page.getByRole('button', { name: '新建工作区', exact: true }).click();
    await page.getByRole('tab', { name: /工作区 1/ }).waitFor();
    await page.locator('.terminal-pane.active .xterm-helper-textarea').focus();
    await page.keyboard.type("printf 'DESKTOP_%s\\n' success");
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => document.querySelector('.terminal-pane.active .xterm-rows')?.textContent.includes('DESKTOP_success'));
    const workspaces = (await page.evaluate(() => window.wangcai.request('workspace', 'config'))).workspaces;
    assert.equal(workspaces.length, 1);
    const localTabs = page.getByRole('tablist', { name: '本机 工作区', exact: true });
    assert.equal(await localTabs.getByRole('tab').count(), 1);
    await page.getByRole('button', { name: '新建工作区', exact: true }).click();
    await localTabs.getByRole('tab', { name: /工作区 2/ }).waitFor();
    await localTabs.getByRole('tab', { name: /工作区 1/ }).click();
    await page.waitForFunction(() => document.querySelector('.terminal-pane.active .xterm-rows')?.textContent.includes('DESKTOP_success'));
    await localTabs.getByRole('button', { name: '结束工作区 2' }).click();
    await page.waitForFunction(() => document.querySelectorAll('.wangcai-workspace [role=tab]').length === 1);
    await page.getByRole('button', { name: '本机', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: '断开', exact: true }).click();
    await page.getByRole('button', { name: '本机', exact: true }).click({ button: 'right' });
    await page.getByRole('menuitem', { name: '连接', exact: true }).click();
    await page.waitForFunction(() => { const button = document.querySelector('[aria-label="新建工作区"]'); return button && !button.disabled; });
    await page.waitForFunction(() => document.querySelector('.terminal-pane.active .xterm-rows')?.textContent.includes('DESKTOP_success'));
    assert.equal((await page.evaluate(() => window.wangcai.request('workspace', 'config'))).workspaces[0].sessionId, workspaces[0].sessionId);
    await page.getByRole('button', { name: /机器设置/ }).click();
    await page.getByLabel('名称', { exact: true }).fill('测试服务器');
    await page.getByLabel('SSH Host', { exact: true }).fill('dev-server');
    await page.getByRole('button', { name: '添加机器', exact: true }).click();
    await page.locator('.machine-setting').filter({ hasText: '测试服务器' }).waitFor();
    const stored = JSON.parse(readFileSync(join(home, '.local/shared/wangcai/data/workspace/config.json'), 'utf8'));
    assert.equal(stored.machines[1].host, 'dev-server');
    assert.equal(stored.workspaces[0].sessionId, workspaces[0].sessionId);
    assert.equal(existsSync(join(home, '.local/shared/wangcai/logs/workspace')), true);
    await page.getByRole('button', { name: '关闭设置' }).click();
    await page.getByRole('button', { name: '测试服务器', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.machine-group[aria-label="本机"] .tab .status-dot')?.classList.contains('connected'));
    await page.getByRole('button', { name: '本机', exact: true }).click();
    await page.getByRole('button', { name: '切换右侧栏' }).click();
    await page.getByRole('button', { name: '新建侧栏标签页' }).click();
    await page.locator('#view-menu').getByRole('button', { name: '文件', exact: true }).click();
    await page.getByRole('tab', { name: '文件', exact: true }).waitFor();
    const storedTabs = JSON.parse(readFileSync(join(home, 'electron-data/tabs.json'), 'utf8'));
    assert.deepEqual(storedTabs, [{ plugin: 'files', id: 'directory', workspaceId: workspaces[0].id }]);
    await page.screenshot({ path: 'tests/dist/screenshots/desktop.png' });
    await desktop.close(); desktop = undefined;
    page = await launch();
    await page.getByRole('tab', { name: /工作区 1/ }).waitFor();
    await page.waitForFunction(() => document.querySelector('.terminal-pane.active .xterm-rows')?.textContent.includes('DESKTOP_success'));
    assert.equal((await page.evaluate(() => window.wangcai.request('workspace', 'config'))).workspaces[0].sessionId, workspaces[0].sessionId);
    await page.getByRole('tab', { name: '文件', exact: true }).waitFor();
    await page.getByRole('button', { name: /机器设置/ }).click();
    await page.locator('.machine-setting').filter({ hasText: '测试服务器' }).getByRole('button', { name: '移除' }).click();
    assert.equal((await page.evaluate(() => window.wangcai.request('workspace', 'config'))).machines.length, 1);
    await page.getByRole('button', { name: '关闭设置' }).click();
    await page.getByRole('button', { name: '结束工作区 1' }).click();
    await page.waitForFunction(() => document.querySelectorAll('.wangcai-workspace [role=tab]').length === 0);
    assert.deepEqual((await page.evaluate(() => window.wangcai.request('workspace', 'config'))).workspaces, []);
    await desktop.close(); desktop = undefined;
    const { resolveConfig } = await import('electron-vite');
    const { createServer } = await import('vite');
    const { config: viteConfig } = await resolveConfig({ root: resolve('desktop') }, 'serve');
    devServer = await createServer({ ...viteConfig.renderer, configFile: false, server: { port: 0, host: '127.0.0.1' } });
    await devServer.listen();
    env.ELECTRON_RENDERER_URL = `http://127.0.0.1:${devServer.httpServer.address().port}`;
    page = await launch();
    await page.waitForFunction(() => document.querySelectorAll('.wangcai-workspace [role=tab]').length === 0);
  } finally {
    if (desktop) await desktop.close().catch(() => {});
    await devServer?.close();
    try { execFileSync(resolve('wangcaicli/dist/debug/wangcai'), ['server', 'stop'], { env, stdio: 'ignore', timeout: 5000 }); } catch {}
    rmSync(home, { recursive: true, force: true });
  }
});
