const { test } = require('node:test');
const assert = require('node:assert/strict');
const { _electron: electron } = require('playwright');
const { mkdtempSync, mkdirSync, writeFileSync, rmSync, realpathSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join, resolve } = require('node:path');
const { execFileSync } = require('node:child_process');

test('Git tab follows terminal cwd and displays two read-only diffs', { timeout: 90000 }, async () => {
  const home = realpathSync(mkdtempSync(join(tmpdir(), 'wangcai-git-ui-')));
  const env = { ...process.env, HOME: home, SHELL: '/bin/bash' };
  delete env.ELECTRON_RUN_AS_NODE;
  let desktop;
  try {
    const repo = join(home, "repo with 'quote");
    mkdirSync(repo);
    const git = (...args) => execFileSync('git', ['-C', repo, ...args], { env, encoding: 'utf8' });
    git('init', '-q', '-b', 'main'); git('config', 'user.name', 'UI Test'); git('config', 'user.email', 'ui@test.local');
    writeFileSync(join(repo, 'sample.ts'), 'const value = "ORIGINAL_VALUE";\n');
    git('add', '.'); git('commit', '-qm', 'initial UI commit');
    writeFileSync(join(repo, 'sample.ts'), 'const value = "STAGED_VALUE";\n'); git('add', '.');
    writeFileSync(join(repo, 'sample.ts'), 'const value = "WORKTREE_VALUE";\n');
    desktop = await electron.launch({ args: ['desktop', `--user-data-dir=${join(home, 'electron')}`], env });
    const page = await desktop.firstWindow();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.getByRole('button', { name: '机器设置' }).waitFor();
    await page.getByRole('button', { name: '切换右侧栏' }).click();
    await page.getByRole('button', { name: '新建侧栏标签页' }).click();
    await page.locator('#view-menu').getByRole('button', { name: 'Git', exact: true }).click();
    await page.getByText('请选择一个已连接的终端', { exact: true }).waitFor();
    await page.locator('.status-dot.connected').waitFor();
    await page.getByRole('button', { name: '新建终端', exact: true }).click();
    await page.locator('.git-note[role=alert]').filter({ hasText: 'not a git repository' }).waitFor();
    const sessions = await page.evaluate(() => window.wangcai.request('terminal', 'terminal', { id: 'local', op: 'list', params: {} }));
    const sessionId = sessions[0].id;
    await page.evaluate(({ repo, sessionId }) => window.wangcai.request('terminal', 'terminal', { id: 'local', op: 'input', params: { session_id: sessionId, data: `cd '${repo.replaceAll("'", "'\\''")}'\r` } }), { repo, sessionId });
    await page.locator('.xterm-screen').filter({ hasText: 'repo with' }).waitFor();
    await page.getByRole('button', { name: '刷新 Git' }).click();
    await page.locator('.git-root').filter({ hasText: repo }).waitFor();
    await page.getByRole('button', { name: /initial UI commit/ }).waitFor();
    const staged = page.locator('.git-rail > details').filter({ has: page.locator('summary', { hasText: /^已暂存/ }) });
    await staged.locator('.git-file > button').first().click();
    await page.locator('.git-editor .view-lines').filter({ hasText: 'STAGED_VALUE' }).waitFor();
    assert.equal(await page.locator('.git-pane').count(), 1);
    const worktree = page.locator('.git-rail > details').filter({ has: page.locator('summary', { hasText: /^未暂存/ }) });
    await worktree.getByRole('button', { name: '并排查看 sample.ts' }).click();
    await page.locator('.git-pane').nth(1).locator('.git-editor .view-lines').filter({ hasText: 'WORKTREE_VALUE' }).waitFor();
    assert.equal(await page.locator('.git-pane').count(), 2);
    assert.equal(await page.locator('.sidebar-tab').count(), 1);
    assert.equal(await page.locator('.git-diff[data-reading=split]').count(), 2);
    await page.getByRole('button', { name: '双栏', exact: true }).click();
    assert.equal(await page.locator('.git-diff[data-reading=inline]').count(), 2);
    await page.getByRole('button', { name: '折行', exact: true }).click();
    assert.equal(await page.locator('.git-diff[data-wrap=false]').count(), 2);
    const workerReady = page.waitForEvent('worker');
    await page.evaluate(() => window.MonacoEnvironment.getWorker('', 'editorWorkerService'));
    const worker = await workerReady;
    assert.equal(await worker.evaluate(() => typeof self.onmessage), 'function');
    await page.getByRole('button', { name: '关闭 diff 2' }).click();
    assert.equal(await page.locator('.git-pane').count(), 1);
    await page.locator('.git-commit-files .git-file > button').first().click();
    await page.locator('.git-editor .view-lines').filter({ hasText: 'ORIGINAL_VALUE' }).waitFor();
    await page.getByRole('button', { name: '新建侧栏标签页' }).click();
    await page.locator('#view-menu').getByRole('button', { name: 'Git', exact: true }).click();
    assert.equal(await page.locator('.sidebar-tab').count(), 1);
    await page.evaluate(({ home, sessionId }) => window.wangcai.request('terminal', 'terminal', { id: 'local', op: 'input', params: { session_id: sessionId, data: `cd '${home}'\r` } }), { home, sessionId });
    await page.getByRole('button', { name: '刷新 Git' }).click();
    await page.locator('.git-note[role=alert]').filter({ hasText: 'not a git repository' }).waitFor();
    await page.locator('.machine-row').click({ button: 'right' });
    await page.getByRole('menuitem', { name: '断开', exact: true }).click();
    await page.getByText('请选择一个已连接的终端', { exact: true }).waitFor();
    assert.deepEqual(errors, []);
  } finally {
    await desktop?.close();
    try { execFileSync(resolve('wangcaicli/dist/debug/wangcai'), ['server', 'stop'], { env, stdio: 'ignore' }); } catch {}
    rmSync(home, { recursive: true, force: true });
  }
});
